### ISSUE TITLE
How to understud Specky-Check.

### ISSUE THREAD

**Issue by Mae72DE** [nschloe/specky#5]
I don't find the manual for Specky-Check, but try to test my FLAC-File.

```
C:\> specky-check
usage: specky-check [-h] [--version] path
specky-check: error: the following arguments are required: path

C:\> specky-check --version
specky unknown [Python 3.7.2]
Copyright (c) 2020 Nico Schlömer

C:\> specky-check .

C:> ffmpeg -i "test.flac" "test.mp3"
C:\> specky-check .
 [32m.\test.mp3 seems good [64 kbps]. [0m

C:> ffmpeg -i "test.flac" "test.wav"
C:> specky-check "test.wav"
 [31mtest.wav is WAV, but has max frequency about 5502 Hz. Check with speck-show. [0m
```

• What does `[××m` mean?

But evereythink seems to be allright. The FLAC-Test-File was a very upscaled MP3 File.
I miss just a better documentation, like a Version-Numer and a more Helpfull text:

```
 Usage: Speck-Check.[exe] [-h] [--version] [mp3-Path]
 Version: 2020-11-09 6:39
 Copyright (c) 2020 Nico Schlömer
 Path to search for MP3 Files to check
 or Speck-Check also acceppt WAV-Files
 and Returns just a Message hard to use in a Cmd-Batch-Script...
```

**Comment by nschloe** [comment]
`-h`/`--help` not good enough?

**Comment by Mae72DE** [comment]
The Help don't tell me that this Programm just like to check MP3 and also WAV Files.
It also don't tell me what the output means. So I don't know how to use this Program if I like to use it in a Script that work with that output.
That's why I think the Help is not good enough.
And I also think the Output should become a little more clear to understand. I don't know what the [0m and [31m should tell me.
And I also hope the next Version become a Version-Numer or just a Date to compare agains old versions.

**Comment by nschloe** [comment]
For me, `specky-check -h` shows
```
usage: specky-check [-h] [--version] path

Check spectrum of audio file

positional arguments:
  path           audio file or directory to analyze

optional arguments:
  -h, --help     show this help message and exit
  --version, -v  display version information
```
I find this quite clear, but then again it was written by me. What's unclear about "Check spectrum of audio file"?

> And I also think the Output should become a little more clear to understand

In what way?

>  I don't know what the [0m and [31m should tell me.

That's a misconfigured terminal. Those are color codes that make the text appear red, but you can just ignore it.

> And I also hope the next Version become a Version-Numer or just a Date to compare agains old versions.

`--version`, see the help.

**Comment by Mae72DE** [comment]
So I tried that, I give the Path (Dot is the Path of the current Direcotry, the is a Audiofile allready in there)
>  `C:\> specky-check .`

But nothing happens.
Than I convet the Sound file using ffmpeg and start the Command again:

> ' C:> ffmpeg -i "test.flac" "test.mp3"'
 ' C:\> specky-check .'
 ' [32m.\test.mp3 seems good [64 kbps]. [0m'

It would be fine if it says me the support audio-files, cause FLAC-Format seens not.

**Comment by nschloe** [comment]
It supports FLAC now.
